- name: Add users to sudoers with no password prompt
  lineinfile:
    path: /etc/sudoers
    line: "{{ item }} ALL=(ALL) NOPASSWD:ALL"
    validate: '/usr/sbin/visudo -cf %s'
  loop:
    - user1
    - user2
    - user3
